version: '3.8'

services:

  redis:
      image: "redis:latest"
      
  researchgpt:
    image: python:3.9-slim
    build:
      context: . 
      target: researchgpt-img
    ports:
      - '8000:8000'
    